# Generated by Django 3.2.3 on 2021-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_alter_admission_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='room_no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
